### ISSUE TITLE
Remove PKI Service

### ISSUE THREAD

**Issue by ElRaptorus** [essential-projects/security_service_contracts#5]
#### Describe your issue

The PKI Service doesn't serve any useful purpose.
It stores private/public key files in its **config** file, as **clear text**!

This is wrong on so many levels and should be changed.

We should remove this service altogether and instead retrieve the key files for a specific user directly through the security service (via `fs.readFileSync`).

In the contracts package, we need two new methods for retrieving a users keyfile, so that these methods can still be accessed by the IAM service.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ppoetschke** [comment]
Is this discussed already internally? The intention of the PKI service is to build an abstraction layer for certificate management. This way an implementation of providing keys not only with files but also with access to central identity management platforms should be easier as directly accessing key files in the security service.
It was certainly known that storing keys in the config is only a simple not production ready example implementation. Why not improving the PKI service?

**Comment by 5ebastianMeier** [comment]
@ppoetschke I think this is more about responsibilities - we can still expand functionality and have the ability to hide key retrieval behind an abstraction further down the line.

But imo that is not reason enough to have a standalone package - as well as another contracts package - besides the already existing security packages that can deal with that.

**Comment by ppoetschke** [comment]
@5ebastianMeier Sure, I only wanted to point out, that there was indeed a useful purpose of the PKI service, at least the intention behind it.
